- name: Pull Docker Image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Pull image
    docker_image:
      name: ujjwalagarwal0575/calculator:latest
      source: pull

  - name: Start Docker service
    service:
      name: docker
      state: started

  - name: Running container
    shell: docker run -it -d --name Calculator ujjwalagarwal0575/calculator
